add_executable(tests_utilities TestUtilities.cpp TestUnicode.cpp TestOperationContext.cpp)
target_link_libraries(tests_utilities PRIVATE Catch2::Catch2WithMain LLUtils::LLUtils Threads::Threads)
add_dependencies(tests_utilities tests_logging_process)
target_compile_definitions(tests_utilities PRIVATE LLUTILS_TEST_PROCESS="$<TARGET_FILE:tests_logging_process>")
if(WIN32)
    target_compile_definitions(tests_utilities PRIVATE UNICODE _UNICODE NOMINMAX)
endif()
set_target_properties(tests_utilities PROPERTIES CXX_STANDARD 23 CXX_STANDARD_REQUIRED YES)
add_test(NAME llutils.utilities COMMAND tests_utilities --reporter compact)
set_tests_properties(llutils.utilities PROPERTIES LABELS "LLUtils;Utilities")
