#pragma once
#if defined(__GNUC__) || defined(__clang__)
    #define LLUTILS_DO_PRAGMA(X) _Pragma(#X)
    #define LLUTILS_DISABLE_WARNING_PUSH           LLUTILS_DO_PRAGMA(GCC diagnostic push)
    #define LLUTILS_DISABLE_WARNING_POP            LLUTILS_DO_PRAGMA(GCC diagnostic pop) 
    #define LLUTILS_DISABLE_WARNING(warningName)   LLUTILS_DO_PRAGMA(GCC diagnostic ignored #warningName)
    
    #define LLUTILS_DISABLE_WARNING_UNUSED_PARAMETER                LLUTILS_DISABLE_WARNING(-Wunused-parameter)
    #define LLUTILS_DISABLE_WARNING_UNREFERENCED_FUNCTION           LLUTILS_DISABLE_WARNING(-Wunused-function)
    #define LLUTILS_DISABLE_WARNING_STRUCTURE_PADDING               LLUTILS_DISABLE_WARNING(-Wmicrosoft-template-shadow)
    #define LLUTILS_DISABLE_WARNING_DOCUMENTATION                   LLUTILS_DISABLE_WARNING(-Wdocumentation)
    #define LLUTILS_DISABLE_WARNING_DOCUMENTATION_PEDANTIC          LLUTILS_DISABLE_WARNING(-Wdocumentation-pedantic)
    #define LLUTILS_DISABLE_WARNING_MICROSOFT_ENUM_VALUE            LLUTILS_DISABLE_WARNING(-Wmicrosoft-enum-value)
    #define LLUTILS_DISABLE_WARNING_ZERO_AS_NULL_POINTER            LLUTILS_DISABLE_WARNING(-Wzero-as-null-pointer-constant)
    #define LLUTILS_DISABLE_WARNING_OLD_STYLE_CAST                  LLUTILS_DISABLE_WARNING(-Wold-style-cast)
    #define LLUTILS_DISABLE_WARNING_LANGUAGE_EXTENSION              LLUTILS_DISABLE_WARNING(-Wlanguage-extension-token)
    #define LLUTILS_DISABLE_WARNING_SWITCH_ENUM                     LLUTILS_DISABLE_WARNING(-Wswitch-enum)
    #define LLUTILS_DISABLE_WARNING_MISSING_VARIABLE_DECLERATIONS   LLUTILS_DISABLE_WARNING(-Wmissing-variable-declarations)
    #define LLUTILS_DISABLE_WARNING_SIGN_CONVERSION                 LLUTILS_DISABLE_WARNING(-Wsign-conversion)
    #define LLUTILS_DISABLE_WARNING_SHORTEN_64_TO_32                LLUTILS_DISABLE_WARNING(-Wshorten-64-to-32)
    #define LLUTILS_DISABLE_WARNING_UNUSED_TEMPLATE                 LLUTILS_DISABLE_WARNING(-Wunused-template)
    #define LLUTILS_DISABLE_WARNING_EXTRA_SEMI                      LLUTILS_DISABLE_WARNING(-Wextra-semi)
    #define LLUTILS_DISABLE_WARNING_EXTRA_SEMI_STATEMENT            LLUTILS_DISABLE_WARNING(-Wextra-semi-stmt)
    #define LLUTILS_DISABLE_WARNING_MISSING_PROTOTYPES              LLUTILS_DISABLE_WARNING(-Wmissing-prototypes)
    #define LLUTILS_DISABLE_WARNING_ANONYMOUS_STRUCT                LLUTILS_DISABLE_WARNING(-Wgnu-anonymous-struct)
    #define LLUTILS_DISABLE_WARNING_NESTED_ANNONYMOUS_TYPES         LLUTILS_DISABLE_WARNING(-Wnested-anon-types)
    #define LLUTILS_DISABLE_WARNING_SEMICOLON_OUTSIDE_FUNCTION      LLUTILS_DISABLE_WARNING(-Wextra-semi)
    #define LLUTILS_DISABLE_WARNING_CONVERT_INT_TO_CHAR            
    #define LLUTILS_DISABLE_WARNING_CONVERT_INT_TO_WCHAR_T
    #define LLUTILS_DISABLE_WARNING_RESEREVED_IDENTIFIER            LLUTILS_DISABLE_WARNING(-Wreserved-identifier)
    #define LLUTILS_DISABLE_WARNING_CAST_FUNCTION_TYPE              LLUTILS_DISABLE_WARNING(-Wcast-function-type)


    




   // other warnings you want to deactivate... 
#elif defined(_MSC_VER)
#define LLUTILS_DISABLE_WARNING_PUSH           __pragma(warning( push ))
#define LLUTILS_DISABLE_WARNING_POP            __pragma(warning( pop )) 
#define LLUTILS_DISABLE_WARNING(warningNumber) __pragma(warning( disable : warningNumber ))

#define LLUTILS_DISABLE_WARNING_UNUSED_PARAMETER                 LLUTILS_DISABLE_WARNING(4100)
#define LLUTILS_DISABLE_WARNING_UNREFERENCED_FUNCTION            LLUTILS_DISABLE_WARNING(4505)
#define LLUTILS_DISABLE_WARNING_STRUCTURE_PADDING                LLUTILS_DISABLE_WARNING(4324)
#define LLUTILS_DISABLE_WARNING_SHORTEN_64_TO_32                 LLUTILS_DISABLE_WARNING(4244)
#define LLUTILS_DISABLE_WARNING_DOCUMENTATION
#define LLUTILS_DISABLE_WARNING_DOCUMENTATION_PEDANTIC
#define LLUTILS_DISABLE_WARNING_MICROSOFT_ENUM_VALUE
#define LLUTILS_DISABLE_WARNING_ZERO_AS_NULL_POINTER
#define LLUTILS_DISABLE_WARNING_OLD_STYLE_CAST
#define LLUTILS_DISABLE_WARNING_LANGUAGE_EXTENSION  
#define LLUTILS_DISABLE_WARNING_SWITCH_ENUM         
#define LLUTILS_DISABLE_WARNING_MISSING_VARIABLE_DECLERATIONS
#define LLUTILS_DISABLE_WARNING_SIGN_CONVERSION
#define LLUTILS_DISABLE_WARNING_UNUSED_TEMPLATE                  
#define LLUTILS_DISABLE_WARNING_EXTRA_SEMI                       
#define LLUTILS_DISABLE_WARNING_EXTRA_SEMI_STATEMENT             
#define LLUTILS_DISABLE_WARNING_MISSING_PROTOTYPES            
#define LLUTILS_DISABLE_WARNING_ANONYMOUS_STRUCT
#define LLUTILS_DISABLE_WARNING_NESTED_ANNONYMOUS_TYPES
#define LLUTILS_DISABLE_WARNING_SEMICOLON_OUTSIDE_FUNCTION       
#define LLUTILS_DISABLE_WARNING_CONVERT_INT_TO_CHAR              LLUTILS_DISABLE_WARNING(4242)
#define LLUTILS_DISABLE_WARNING_CONVERT_INT_TO_WCHAR_T           LLUTILS_DISABLE_WARNING(4365)
#define LLUTILS_DISABLE_WARNING_RESEREVED_IDENTIFIER
#define LLUTILS_DISABLE_WARNING_CAST_FUNCTION_TYPE

#else
    #define DISABLE_WARNING_PUSH
    #define DISABLE_WARNING_POP
    #define DISABLE_WARNING_UNREFERENCED_FORMAL_PARAMETER
    #define DISABLE_WARNING_UNREFERENCED_FUNCTION
    // other warnings you want to deactivate... 
 
#endif